### ISSUE TITLE
Get-MyTask produces no output, only when adding -All parameter

### ISSUE THREAD

**Issue by KurtDeGreeff** [jdhitsolutions/MyTasks#15]
### PSVersion Table

Name                           Value                                                                                                                                   
----                           -----                                                                                                                                   
PSVersion                      5.1.16299.98                                                                                                                            
PSEdition                      Desktop                                                                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                 
BuildVersion                   10.0.16299.98                                                                                                                           
CLRVersion                     4.0.30319.42000                                                                                                                         
WSManStackVersion              3.0                                                                                                                                     
PSRemotingProtocolVersion      2.3                                                                                                                                     
SerializationVersion           1.1.0.1                                                                                                                                 

### What is the syntax or expression you are using?
Get-MyTask

### What happens?
No Output

### What do you think should happen?
When specifying -All parameter, tasks are showing

![image](https://user-images.githubusercontent.com/2629743/34737898-cddfb802-f577-11e7-9d0f-7ec26f86c4f5.png)

**Comment by jdhitsolutions** [comment]
I changed the default behavior of `Get-MyTask` to only display tasks due in the next 30 days.  This is a breaking change that I may not have documented well enough. Since you only have 1 task due in October, the command doesn't give you any result.

I use this module heavily and already have 26 tasks for the year. But I only really need to see upcoming tasks by default.

One thing you can do is add a default parameter value:
```
$PSDefaultParameterValues."Get-MyTask:DaysDue" = 365
```
The DaysDue parameter is now the default and it is set to 30.

**Comment by jdhitsolutions** [comment]
I've updated the [README](https://github.com/jdhitsolutions/MyTasks/blob/master/README.md) file to make this clearer.
