### ISSUE TITLE
Show-MyTask gives error...only when adding -All parameter it's ok

### ISSUE THREAD

**Issue by KurtDeGreeff** [jdhitsolutions/MyTasks#16]
![image](https://user-images.githubusercontent.com/2629743/34738031-1b4c0c94-f578-11e7-9d72-5da71eaa44ec.png)

**Comment by jdhitsolutions** [comment]
This too is using a default value of 30 days. If there are no matching events then you should get nothing. This is in fact a bug with Show-MyTask.

**Comment by jdhitsolutions** [comment]
fixed in commit https://github.com/jdhitsolutions/MyTasks/commit/6ac4929d28d4f3f00c5238fa37dadc9f63d21ea2

v1.31. of the module has also been pushed to the PowerShell Gallery. Now you will get a warning message if no tasks are found.

**Comment by KurtDeGreeff** [comment]
Thanks, good idea to give warning
