### ISSUE TITLE
Can you add in future release of this module comments (notes) to tasks ?

### ISSUE THREAD

**Issue by adymer** [jdhitsolutions/MyTasks#19]
### PSVersion Table
Name                           Value                                                                                                                                                                        
----                           -----                                                                                                                                                                        
PSVersion                      5.1.16299.248                                                                                                                                                                
PSEdition                      Desktop                                                                                                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                      
BuildVersion                   10.0.16299.248                                                                                                                                                               
CLRVersion                     4.0.30319.42000                                                                                                                                                              
WSManStackVersion              3.0                                                                                                                                                                          
PSRemotingProtocolVersion      2.3                                                                                                                                                                          
SerializationVersion           1.1.0.1 

### What is the syntax or expression you are using?
It is possible in a future release to add an Info or Comment with Set-Mytask as how you solve a task or ToDo . 
Example:
Get-MyTask -Name "......." | Set-MyTask -comment(or -note) "how you solved the task(problem)"

**Comment by jdhitsolutions** [comment]
That's what I had in mind for the description property. I wonder if I should just rename that to Comment.

**Comment by adymer** [comment]
Hi . This module is perfect as it is . Description should stay . My question was because I use Kanboard and for example  I start a task , put in the description and along doing (solving) the task I keep add some comments to note the steps that were done in solving the problem (task) . You have done a great job with this and all your other projects .

**Comment by adymer** [comment]
And I started to use this for myself (kanboard we use for team work )and I really like it because it does exactly what should do and all this directly the lovely Powershell window :)

**Comment by jdhitsolutions** [comment]
I'm going to leave this as is.
