### ISSUE TITLE
Get following error when using Show-MyTask..

### ISSUE THREAD

**Issue by KurtDeGreeff** [jdhitsolutions/MyTasks#2]
Write-Host : Cannot process the color because -1 is not a valid color.
Parameternaam: value
Werkelijke waarde was -1.
At C:\MyTasks\myTasksFunctions.ps1:639 char:9
+         Write-Host $_ -ForegroundColor $c
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Write-Host], ArgumentOutOfRangeException
    + FullyQualifiedErrorId : SetInvalidForegroundColor,Microsoft.PowerShell.Commands.WriteHostCommand

**Comment by jdhitsolutions** [comment]
Show-Mytask may not work properly in the PowerShell ISE. Although it does for me in v5 on Windows 8.1. What version of PowerShell are you running and on what operating system? 
I might need to add some code to that function to test the host.

**Comment by KurtDeGreeff** [comment]
I'm using W10 x64 V1607 (build 14372)

PSVersion                      5.1.14372.0                                                                                                                               
PSEdition                      Desktop                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.14372.0}                                                                                                    
BuildVersion                   10.0.14372.0                                                                                                                              
CLRVersion                     4.0.30319.42000                                                                                                                           
WSManStackVersion              3.0                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                       
SerializationVersion           1.1.0.1

**Comment by jdhitsolutions** [comment]
The ISE changed a bit in Windows 10 so this doesn't surprise me. But I'll take a look to see if there is anything I can do differently. Otherwise I may have to go with my original thought and check the host when running Show-MyTask.

**Comment by jdhitsolutions** [comment]
I've pushed a new change that takes a different approach and this should work in the Windows 10 ISE.

**Comment by jdhitsolutions** [comment]
This should now work in the ISE and console on Windows 10. If there is still an issue we can re-open.

**Comment by KurtDeGreeff** [comment]
Ok, I can confirm it works, many thanks!
