### ISSUE TITLE
Unable to use this module using United Kingdom datetime format.

### ISSUE THREAD

**Issue by duk3ofed** [jdhitsolutions/MyTasks#23]
### PSVersion Table

Name                           Value                                                                                                                                                                                                  
----                           -----                                                                                                                                                                                                  
PSVersion                      5.1.16299.251                                                                                                                                                                                          
PSEdition                      Desktop                                                                                                                                                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                                
BuildVersion                   10.0.16299.251                                                                                                                                                                                         
CLRVersion                     4.0.30319.42000                                                                                                                                                                                        
WSManStackVersion              3.0                                                                                                                                                                                                    
PSRemotingProtocolVersion      2.3                                                                                                                                                                                                    
SerializationVersion           1.1.0.1                                                                                                                                                                                                

### What is the syntax or expression you are using?
Get-MyTask

### What happens?

ERROR: _ImportTasks : Cannot convert argument "1", with value: "23/04/2018 14:37:00", for "MyTask" to type "System.DateTime": "Cannot convert value "23/04/2018 14:37:00" to type "System.DateTime". Error: "String was not recognized as a
valid DateTime.""

### What do you think should happen?

It should return my tasks without error. I can confirm that I am in the UK, and thus the dateTime format differs from your module. If I enter a due date for a new task using a date which suits both regions i.e. 5/5/2018, I am able to retrieve that particular task ok using the Get-MyTask cmdlet.

**Comment by shaneis** [comment]
Hey @duk3ofed check out the PR from @Windos
Works for me with my UK datetime format

**Comment by jdhitsolutions** [comment]
I am sure it does. I have been on the road allot this year and have not had a chance to look at this.

**Comment by jdhitsolutions** [comment]
Update to 1.5.0 from the PowerShell Gallery and see if this fixes the problem.
