### ISSUE TITLE
Remove-MyTask gives an error only when using ID parameter.

### ISSUE THREAD

**Issue by KurtDeGreeff** [jdhitsolutions/MyTasks#3]
Parameter is called TaskID in Remove-MyTask, maybe better rename it to ID like with Set-MyTask..
Removing by name works fine, but by ID give error:

remove-mytask -TaskID 2
Remove-MyTask : Cannot process argument transformation on parameter 'TaskID'. Cannot convert value "2" to type "System.Guid". Error: "GUID moet uit 32 cijfers en 4 stree
pjes bestaan (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)."
At line:1 char:23
+ remove-mytask -TaskID 2
+                       ~
    + CategoryInfo          : InvalidData: (:) [Remove-MyTask], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Remove-MyTask

**Comment by jdhitsolutions** [comment]
I need to provide better documentation for this command. The task object has an ID property which you see. There is also a TaskID property which is hidden and contains a unique GUID for each task. You can see them by running a command like this: get-mytask | format-list -view all

Or the better solution might be to revise the function to use InputObject. Right now, that is the way that TaskID parameter is being used. The assumption is piping from Get-MyTask to Remove-MyTask.

**Comment by KurtDeGreeff** [comment]
Get-MyTask | Remove-MyTask makes sense. 
Maybe another shorthand option for Remove-MyTask, if it makes sense,  using a parameter alias attribute ID for TaskID..

**Comment by jdhitsolutions** [comment]
I've pushed a new version which should address this issue.

**Comment by jdhitsolutions** [comment]
Closing for now. If this is still an issue we can re-open.
