### ISSUE TITLE
Configuration Naming Conventions

### ISSUE THREAD

**Issue by thecliguy** [jdhitsolutions/MyTasks#38]
Thank you for implementing #36. The reason I advocated the function name `Get-myTaskPath` is because there was already a `Set-myTaskPath`, so it seemed the logical counterpart . Having now read through the code relating to configuration files a little more closely I've come to the conclusion that this may not be the best name...

Configuration consists of the following:
  1. `$myTaskHome`        The folder in which configuration files reside.
  1. `$myTaskPath`        The file in which tasks reside.
  1. `$myTaskArchivePath` The file in which archived tasks reside.
  1. `$myTaskCategory`    The file in which task categories are stored.

The function `Set-myTaskPath` gives the impression that you're only modifying `$myTaskPath` but that's not the case, you're actually modifying `$myTaskHome` which consequently affects `$myTaskPath`, `$myTaskArchivePath` and `$myTaskCategory`. So I think this function really ought to be named `Set-myTaskHome`. 

If you were to change `Set-myTaskPath` to `Set-myTaskHome` then by extension `Get-myTaskPath` should become `Get-myTaskHome`. Currently `Get-myTaskPath` returns all of the configuration variables. If you were to replace it with `Get-myTaskHome` then I think it should only return `$myTaskHome`, the rationale being that user's shouldn't be setting the values of the other config variables independently, they should only ever change `$myTaskHome`, so they've no need to see the other values. Also, semantically, returning `$myTaskHome` is the only outcome that really makes sense.

Lastly, `$myTaskPath` is too ambiguous a name. It doesn't convey that it's the path to the file containing the actual task records. I would suggest something like `$myTaskRecords` _(if you did this you'd also have to change `$myTaskArchivePath` to `$myTaskArchiveRecords`)_. I wouldn't bother changing the value name (`myTasks.xml`), it's fine as it is and if you did it would be a breaking change.

Naming and conventions are somewhat subjective, so what I think is rational you might not. If you do have the appetite to thrash this out then I'm more than happy to debate it with you for a bit and see if we can reach a consensus...?

**Comment by jdhitsolutions** [comment]
I appreciate the feedback.  This is a great example of what happens when a project organically grows in scope. I'll have to think about what I can to to clean up the semantics but without breaking anything.

**Comment by jdhitsolutions** [comment]
I could probably handle the commands with aliases to avoid breaking things. I'm afraid that the variable names are too entrenched to change them. Although you should never have to deal with them directly now that there a functions to manage them.

**Comment by thecliguy** [comment]
Regarding aliases, is this what you're thinking in practice?
  * The function `Set-myTaskPath` is renamed `Set-myTaskHome`.
  * An alias `Set-myTaskPath` is created which references `Set-myTaskHome`.

Regrading `Get-myTaskPath`, it was **only just** introduced, so do you just drop it and use `Get-myTaskHome` in the next release? _Technically_ that would be a breaking change but perhaps you can get away with it given that it was **only just** introduced... Or do you alias `Get-myTaskPath` to `Get-myTaskHome`?

**Comment by jdhitsolutions** [comment]
That's essentially what I was thinking.

**Comment by jdhitsolutions** [comment]
v2.1.0 has been published to the PowerShell Gallery with these changes.

**Comment by thecliguy** [comment]
I've tested `Get-myTaskHome`, `Set-myTaskHome`, `Get-myTaskPath` and `Set-myTaskPath`.

The only thing I'd question _(which I alluded to before)_, is whether `Get-myTaskHome` should only return `$myTaskHome` as the name suggests, rather than return all configuration related variables?

**Comment by jdhitsolutions** [comment]
I decided to return all variables so you could see the values. The idea is that you use the functions to manage the variables and never have to deal with them directly. I suppose technically I'm showing more than the command name would suggest but I don't see any harm. At most I'm bending a scripting best practice.
