### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by CollinChaffin** [jdhitsolutions/MyTasks#39]
# Issue

## PSVersion Table
```
λ  $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14409.1018
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1018
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
## What is the syntax or expression you are using?

```
Get-Task
Show-Task -All
```

## What happens?

Tasks set up last year clearly overdue show overdue "FALSE", no color etc. simply appear to not be doing anything with the data as far as tracking via due dates. I even have them in two different categories.  Screenshot:

![SNAG_3-8-2019_20-07-18](https://user-images.githubusercontent.com/9301483/54064867-756af600-41de-11e9-9ebe-1db8cd9b4f94.png)

## What do you think should happen?

Indicate they were due (never did) and 2 tasks over half a year overdue still show overdue false with no indicator coloring alert etc. as shown in screenshot above.  Is there something I've missed requiring I set a task as "started" or something above and beyond simply creating it with a due date?

**Comment by jdhitsolutions** [comment]
I noticed this too a few days ago. I think I have it fixed.  Pushing v2.2.0 now that should address this.

**Comment by jdhitsolutions** [comment]
This should work now. It does for me.
