### ISSUE TITLE
Need to add Encoding UTF8

### ISSUE THREAD

**Issue by evgend** [jdhitsolutions/MyTasks#4]
For better support of other languages, need to add parameter Encoding UTF8 to Add-Content, Get-Content, Set-Content

**Comment by jdhitsolutions** [comment]
So you're saying make UTF8 the default? Given that I'm working with XML files that might make the most sense. If you create custom categories, that is a stored in a text file. Are you finding that to be a problem?

**Comment by evgend** [comment]
Ok. I add new cyrillic categories. Then thay reads normally when i run Get-MyTaskCategory
But when i create New-MyTask and than read it, it contains unreadable test.
Examples:
https://s4.postimg.org/xbh8bo3bh/without_UTF8.png
When i add parameter Encoding UTF8.
https://s4.postimg.org/dfl8w4ma5/with_UTF8.png

**Comment by jdhitsolutions** [comment]
Actually I'm wondering if Unicode would be a better default. Can you try again using Unicode as encoding?

**Comment by jdhitsolutions** [comment]
Pushed a new build that uses Unicode for category file.

**Comment by jdhitsolutions** [comment]
Closing for now. If this is still an issue we can re-open it.

**Comment by evgend** [comment]
Now works! Thank you
