### ISSUE TITLE
Show-MyTask Colourisation not working on Multi-line Descriptions.

### ISSUE THREAD

**Issue by shaneis** [jdhitsolutions/MyTasks#40]
# Issue
Show-MyTask does not colour all lines of a multi-line description.

## PSVersion Table

```
Name                           Value
----                           -----
PSVersion                      6.2.0-rc.1
PSEdition                      Core
GitCommitId                    6.2.0-rc.1
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

Noticed this on PSVersion 5.1 first but I've moved over to PSCore now. Will need to re-import the module on 5.1 to retest.

## What is the syntax or expression you are using?

```
C:\> New-MyTask -Name 'Multiline description test.' -Description 'This is a test
To see if multilines can be colourised.

If not, panic.' -Category MyTasks

C:\> Show-MyTask -Category MyTasks
```

## What happens?

MyTasks item is saved correctly.
When the `Show-MyTask` command is run, not all lines of the Description are coloured correctly.

![image](https://user-images.githubusercontent.com/8527247/55072484-2698d980-5083-11e9-9ae7-17f438bd3f7e.png)

## What do you think should happen?

All lines of the Description should be colourised correctly i.e. all red if Overdue, etc.

**Comment by jdhitsolutions** [comment]
That is not too surprising. I assumed descriptions would be short and single line. This could be tricky.

**Comment by shaneis** [comment]
yeah...I figured it wouldn't be too easy.

Normally the name of my tasks are short and the description has more fleshed out information.

I'm not invested in this way though so I can change how I do things to keep them single line.
Can't speak for everyone else though 🤷‍♂️

**Comment by jdhitsolutions** [comment]
Its worth investigating.

**Comment by shaneis** [comment]
Latest release marks the first line as overdue and the subsequent lines in a different colour.

![image](https://user-images.githubusercontent.com/8527247/64256115-abcdc780-cf1a-11e9-984d-b37b85ba14ed.png)

I'm actually okay with this :)
