### ISSUE TITLE
Show-MyTask not colouring 100 progress items if progress doesn't fit on Format-Table screen

### ISSUE THREAD

**Issue by shaneis** [jdhitsolutions/MyTasks#41]
# Issue

## PSVersion Table

```
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.1
PSEdition                      Core
GitCommitId                    7.0.0-preview.1
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## What is the syntax or expression you are using?

`Show-MyTask`

## What happens?

![image](https://user-images.githubusercontent.com/8527247/60872702-13260e80-a22d-11e9-9207-dce88470db61.png)

Task ID 73 is 100% progressed but not showing in green since the Description of Task ID 87 pushes the Progress off the screen.

![image](https://user-images.githubusercontent.com/8527247/60872847-554f5000-a22d-11e9-81fa-82da4ed25e77.png)

## What do you think should happen?

Task ID 73 preferably would show as green.

However, since the regex is done on the `Format-Table | Out-String`, the Progress seems to be not on the screen so isn't picked up by the regex. Since it's not picked up, the colouring isn't done.

The yellow colour warning does work.
Since the regex can't see the Progess, it assumes that the job is not complete. It then checks the DueDate and, if it's less than 24 hours, marks it yellow.
Since this would be a significant change in the way the function works, I'm not sure if this is feasible/worth it.

**Comment by jdhitsolutions** [comment]
I have not done anything with PowerShell 7 yet. Do you see the same behavior with your tasks in Windows PowerShell or PowerShell 6.x if you still have it?

**Comment by jdhitsolutions** [comment]
Ok. I get the same result in PowerShell Core 6.2 and probably Windows PowerShell. The easiest solution may be to limit the length of `Description`.  I should probably also enforce a limit on `Name` as well.

**Comment by jdhitsolutions** [comment]
I'll probably need to incorporate Issue #40 with this.

**Comment by shaneis** [comment]
I'm okay with that.  
It's a bit of abuse having extremely long strings and multi-line descriptions so limiting them is not an issue for me

**Comment by shaneis** [comment]
Can confirm that this is now highlighting all lines of a 100% progress task to Green

Thank you!
