### ISSUE TITLE
Unable to Install MyTasks when psake is already installed

### ISSUE THREAD

**Issue by tiksn** [jdhitsolutions/MyTasks#45]
# Issue

## PSVersion Table

```pwsh
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## What is the syntax or expression you are using

```pwsh
Install-Module -Name MyTasks
```

## What happens

```pwsh
Install-Package: The following commands are already available on this system:'Task'. This module 'MyTasks' may override the existing
commands. If you still want to install this module 'MyTasks', use -AllowClobber parameter.
```

## What do you think should happen

If 'task' alias is removed, we can install and use these 2 packages without problem.

**Comment by jdhitsolutions** [comment]
Let me try some things.

**Comment by jdhitsolutions** [comment]
You should be able to install the module using -AllowClobber. If you only use one module at a time in a PowerShell session there is no conflict. Running `Task` will either run the psake function or the MyTasks alias. If you import both modules, it can get a little trickier. But PowerShell has options. You can specify the full command name like `psake\task`. Or import a module with a prefix.

```powershell
Import-module mytasks -prefix x
```

Now all commands and alias in this module have an 'x` at the beginning of the name. You would run `xTask` or `New-xMyTask`. Given the large number of PowerShell modules, commands, and aliases, conflicts like these are inevitable, but there are ways to handle them.  Installing the module won't remove anything from the psake module.

**Comment by jdhitsolutions** [comment]
The `MyTasks` module is __no longer under active development__. It has been replaced by [PSWorkItem](https://github.com/jdhitsolutions/PSWorkItem). The PSWorkItem module uses the same concepts as MyTasks, but stores tasks, PSWorkItems in the new module, in a SQLite database. Installing PSWorkItem will also install the [MySQLite])https://github.com/jdhitsolutions/MySQLite/) module.  All open issues for MyTasks will be closed.
