### ISSUE TITLE
[Request]: Ability to create a parent / child task relationship

### ISSUE THREAD

**Issue by Tuttu** [jdhitsolutions/MyTasks#47]
### Describe the request

Hello, 

Great module, really handy to manage tasks. 
Have you considered adding a way to create child tasks that would depend on a parent task?

**Comment by jdhitsolutions** [comment]
I have not. I intended this to be a simple reminder system on stuff to do. Adding child tasks begins to turn this module into a project management solution. Do you have a mock-up of what this might look like?

**Comment by Tuttu** [comment]
Yeah, I get your point. I was thinking that it would act like a sub-bullet in a bullet list but I can understand it doesn't go well with your idea for this module. 
As for a mockup, I would have thought of something simple like that which doesn't change your layout and simply adds a visual clue that a task is a child one. It would also sort child task under their parents, no matter their ID.
![image](https://user-images.githubusercontent.com/996797/160343956-c1908c9d-5204-43fc-bc22-7529dd807b1e.png)

**Comment by jdhitsolutions** [comment]
The challenge is that the ID is auto-generated, kind of like job numbers. There is a hidden GUID property to keep everything unique. This module is nothing more than a fancy To-Do manager. But I'll keep this open as a possible feature enhancement.

**Comment by Tuttu** [comment]
Yeah, I figured the unique ID while looking at the XML earlier today. The only thing that could work would be to use the name which can be a mess as well if it's quite long. 😅

**Comment by jdhitsolutions** [comment]
I have long-term plans to revise the module to use a database like SQLIte instead of XML. This might be easier to do with a database layout.

**Comment by Tuttu** [comment]
Nice. Thanks for the heads up. I will continue to use this module. It's already added to my profile so I get a reminder of all the good work I have pending each time I open my Terminal. :D

**Comment by jdhitsolutions** [comment]
The `MyTasks` module is __no longer under active development__. It has been replaced by [PSWorkItem](https://github.com/jdhitsolutions/PSWorkItem). The PSWorkItem module uses the same concepts as MyTasks, but stores tasks, PSWorkItems in the new module, in a SQLite database. Installing PSWorkItem will also install the [MySQLite])https://github.com/jdhitsolutions/MySQLite/) module.  All open issues for MyTasks will be closed.
