### ISSUE TITLE
installation instruction of MyTasks for Powershell on linux

### ISSUE THREAD

**Issue by zaxebo1** [jdhitsolutions/MyTasks#6]
Microsoft had recently officially released powershell for linux too (see https://azure.microsoft.com/en-us/blog/powershell-is-open-sourced-and-is-available-on-linux/ )

Hence, I have just installed Microsoft Powershell on **ubuntu 16.04** , downloaded from https://github.com/PowerShell/PowerShell/releases . 

As there is no installation instruction of your MyTasks module at https://github.com/jdhitsolutions/MyTasks   . Can you add some instruction on how to install your *MyTasks*  module especially on powershell on linux

**Comment by jdhitsolutions** [comment]
The open source version of PowerShell is based on .NET Core which is a subset of the full .NET framework. This means not everything that runs on PowerShell on Windows will work on Linux. This module may be one of them. I seem to recall seeing a limitation on Linux using Select-XML which this module uses alot. I can certainly test this on a Linux build but for now the module is really designed for PowerShell 5 or 5.1 on Windows.

**Comment by zaxebo1** [comment]
oops :-(
