### ISSUE TITLE
SQLite and/or task folders

### ISSUE THREAD

**Issue by elijahgagne** [jdhitsolutions/MyTasks#7]
I am interested in this project because I have previously created from PS functions to manage my tasks. Would you have any interest in either of the following:
 - Changing from XML storage to SQLite? Long term, when you have thousands of tasks, I think there will be some benefits. It will also make it easier to build relationships between additional features you might like to add later such as time tracking or reporting. I will also mention that SQLite should work for Mac/Linux.
 - Creating the ability to optionally tie a folder to a task? Most of my tasks require generating files. E.g. documenting steps I took, downloading vendor docs, creating a script.

**Comment by jdhitsolutions** [comment]
I thought about something like SQLite, but I felt adding it would make the module unnecessarily complex. My intention is that this module is for 10-20 tasks that only you have access to.  A database app would be overkill. But you are certainly welcome to fork the project and incorporate SQLite or anything else.

**Comment by elijahgagne** [comment]
Thanks for considering it!
